// Other agents' hooks, driven through the real bundle with payloads shaped like each
// vendor's docs: Cursor (cursor.com/docs/hooks), Gemini CLI (geminicli.com/docs/hooks),
// Codex CLI (learn.chatgpt.com/docs/hooks).
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const CLI = new URL("../dist/snout.mjs", import.meta.url).pathname;

function project(mode = "enforce") {
  const root = mkdtempSync(join(tmpdir(), "snout-agents-"));
  mkdirSync(join(root, "src"), { recursive: true });
  mkdirSync(join(root, ".snout"), { recursive: true });
  writeFileSync(join(root, ".snout", "config.json"), JSON.stringify({ mode }) + "\n");
  writeFileSync(join(root, "src/app.ts"), "export const a = 1;\n");
  writeFileSync(join(root, "package-lock.json"), JSON.stringify({ d: "x".repeat(20_000) }));
  const gen = Array.from({ length: 2000 }, (_, i) => `export function op${i}(http) { return http.request({ path: "/v1/op${i}" }); }`).join("\n");
  writeFileSync(join(root, "src/client.gen.js"), "// @generated by openapi-generator. DO NOT EDIT.\n" + gen);
  return root;
}

function run(args, payload, cwd) {
  const r = spawnSync(process.execPath, [CLI, ...args], { input: payload === undefined ? "" : JSON.stringify(payload), encoding: "utf8", cwd });
  assert.equal(r.status, 0, r.stderr);
  return r.stdout.trim();
}
const json = (s) => JSON.parse(s);

// ---------- Cursor ----------

const cursorRead = (root, rel) => ({ conversation_id: "c1", generation_id: "g1", hook_event_name: "beforeReadFile", workspace_roots: [root], file_path: join(root, rel), content: "…", attachments: [] });

test("cursor: a lockfile read is denied in enforce, with a note for the user", () => {
  const root = project();
  const out = json(run(["hook", "cursor", "beforeReadFile"], cursorRead(root, "package-lock.json")));
  assert.equal(out.permission, "deny");
  assert.match(out.user_message, /lockfile/i);
});

test("cursor: source is allowed, and the answer is always valid JSON", () => {
  const root = project();
  assert.deepEqual(json(run(["hook", "cursor", "beforeReadFile"], cursorRead(root, "src/app.ts"))), { permission: "allow" });
  assert.deepEqual(json(run(["hook", "cursor", "beforeReadFile"], undefined)), { permission: "allow" }, "empty stdin must still allow: Cursor blocks on invalid output");
});

test("cursor: a file enforce would trim is denied instead, since Cursor cannot trim", () => {
  const root = project();
  assert.equal(json(run(["hook", "cursor", "beforeReadFile"], cursorRead(root, "src/client.gen.js"))).permission, "deny");
});

test("cursor: observe mode allows everything and still records it", () => {
  const root = project("observe");
  assert.equal(json(run(["hook", "cursor", "beforeReadFile"], cursorRead(root, "package-lock.json"))).permission, "allow");
  assert.ok(existsSync(join(root, ".snout", "ledger.jsonl")));
});

test("cursor: `cat` of a lockfile is denied with a search hint for the agent", () => {
  const root = project();
  const out = json(run(["hook", "cursor", "beforeShellExecution"], { conversation_id: "c1", hook_event_name: "beforeShellExecution", workspace_roots: [root], cwd: root, command: "cat package-lock.json" }));
  assert.equal(out.permission, "deny");
  assert.match(out.agent_message, /grep/);
});

// ---------- Gemini CLI ----------

const geminiRead = (root, rel, extra = {}) => ({ session_id: "s1", cwd: root, hook_event_name: "BeforeTool", timestamp: "t", tool_name: "read_file", tool_input: { absolute_path: join(root, rel), ...extra } });

test("gemini: a big generated file is trimmed by rewriting offset and limit (0-based offset)", () => {
  const root = project();
  const out = json(run(["hook", "gemini", "BeforeTool"], geminiRead(root, "src/client.gen.js")));
  assert.equal(out.decision, "allow");
  assert.equal(out.hookSpecificOutput.tool_input.offset, 0);
  assert.ok(out.hookSpecificOutput.tool_input.limit >= 5 && out.hookSpecificOutput.tool_input.limit <= 60);
});

test("gemini: a one-line bundle is denied with a reason", () => {
  const root = project();
  const out = json(run(["hook", "gemini", "BeforeTool"], geminiRead(root, "package-lock.json")));
  assert.equal(out.decision, "deny");
  assert.ok(out.reason.length > 0);
});

test("gemini: a small ranged read passes, and source is left alone", () => {
  const root = project();
  assert.equal(json(run(["hook", "gemini", "BeforeTool"], geminiRead(root, "src/client.gen.js", { offset: 100, limit: 40 }))).decision, undefined);
  assert.deepEqual(json(run(["hook", "gemini", "BeforeTool"], geminiRead(root, "src/app.ts"))), {});
});

test("gemini: AfterTool records the read in the ledger", () => {
  const root = project("observe");
  run(["hook", "gemini", "AfterTool"], { ...geminiRead(root, "package-lock.json"), hook_event_name: "AfterTool", tool_response: { llmContent: "x".repeat(20_000), returnDisplay: "" } });
  const rows = readFileSync(join(root, ".snout", "ledger.jsonl"), "utf8").trim().split("\n").map((l) => JSON.parse(l));
  assert.ok(rows.some((r) => r.rule === "lockfile"), JSON.stringify(rows));
});

// ---------- Codex CLI ----------

test("codex: `cat` of a lockfile is denied in Claude's hook shape", () => {
  const root = project();
  const out = json(run(["hook", "codex", "PreToolUse"], { session_id: "s1", turn_id: "t1", cwd: root, hook_event_name: "PreToolUse", model: "gpt", tool_name: "Bash", tool_use_id: "u1", tool_input: { command: "cat package-lock.json" } }));
  assert.equal(out.hookSpecificOutput.permissionDecision, "deny");
});

test("unknown agent: prints usage and exits 0", () => {
  assert.match(run(["hook", "nope", "x"], {}), /unknown agent/);
});

// ---------- init ----------

test("init writes each agent's config, is safe to re-run, and keeps other hooks", () => {
  const root = project();
  mkdirSync(join(root, ".cursor"));
  writeFileSync(join(root, ".cursor", "hooks.json"), JSON.stringify({ version: 1, hooks: { beforeShellExecution: [{ command: "./other.sh" }] } }));
  for (let i = 0; i < 2; i++) for (const a of ["cursor", "gemini", "codex"]) assert.match(run(["init", a], undefined, root), new RegExp(`snout init ${a}: wrote`));

  const cursor = json(readFileSync(join(root, ".cursor", "hooks.json"), "utf8"));
  assert.equal(cursor.hooks.beforeShellExecution.length, 2, "ours once, plus the existing hook");
  assert.ok(cursor.hooks.beforeShellExecution.some((h) => h.command === "./other.sh"));
  assert.equal(cursor.hooks.beforeReadFile.length, 1);
  assert.match(cursor.hooks.beforeReadFile[0].command, /hook cursor beforeReadFile$/);

  const gemini = json(readFileSync(join(root, ".gemini", "settings.json"), "utf8"));
  assert.equal(gemini.hooks.BeforeTool.length, 1);
  assert.equal(gemini.hooks.BeforeTool[0].matcher, "read_file|run_shell_command");

  const codex = json(readFileSync(join(root, ".codex", "hooks.json"), "utf8"));
  assert.equal(codex.hooks.PreToolUse.length, 1);
  assert.equal(codex.hooks.PreToolUse[0].matcher, "^Bash$");
  assert.match(codex.hooks.PreToolUse[0].hooks[0].command, /hook codex PreToolUse$/);
});
