// `snout mcp`: a full stdio session through the real bundle.
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const CLI = new URL("../dist/snout.mjs", import.meta.url).pathname;

function project() {
  const root = mkdtempSync(join(tmpdir(), "snout-mcp-"));
  mkdirSync(join(root, "src"), { recursive: true });
  writeFileSync(join(root, "src/app.ts"), "export const a = 1;\nexport const b = 2;\n");
  writeFileSync(join(root, ".env"), "TOKEN=abc\n");
  writeFileSync(join(root, "package-lock.json"), JSON.stringify({ d: "x".repeat(20_000) }));
  const gen = Array.from({ length: 2000 }, (_, i) => `export function op${i}(http) { return http.request({ path: "/v1/op${i}" }); }`).join("\n");
  writeFileSync(join(root, "src/client.gen.js"), "// @generated by openapi-generator. DO NOT EDIT.\n" + gen);
  return root;
}

/** Sends the messages, closes stdin, and returns the replies keyed by id. */
function session(root, messages) {
  const input = messages.map((m) => JSON.stringify(m)).join("\n") + "\n";
  const r = spawnSync(process.execPath, [CLI, "mcp", root], { input, encoding: "utf8", timeout: 20_000 });
  assert.equal(r.status, 0, r.stderr);
  const replies = r.stdout.trim().split("\n").filter(Boolean).map((l) => JSON.parse(l));
  return Object.fromEntries(replies.map((x) => [x.id, x]));
}

const call = (id, name, args) => ({ jsonrpc: "2.0", id, method: "tools/call", params: { name, arguments: args } });

test("mcp: initializes, lists its tools, and ignores notifications", () => {
  const r = session(project(), [
    { jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "t", version: "1" } } },
    { jsonrpc: "2.0", method: "notifications/initialized" },
    { jsonrpc: "2.0", id: 2, method: "tools/list" },
    { jsonrpc: "2.0", id: 3, method: "nope" },
  ]);
  assert.equal(r[1].result.serverInfo.name, "snout");
  assert.equal(r[1].result.protocolVersion, "2025-06-18");
  assert.deepEqual(r[2].result.tools.map((t) => t.name), ["snout_read", "snout_classify", "snout_audit_context"]);
  assert.equal(r[3].error.code, -32601);
  assert.equal(Object.keys(r).length, 3, "no reply to a notification");
});

test("mcp: snout_read returns source whole, and a generated file as head plus outline", () => {
  const root = project();
  const r = session(root, [call(1, "snout_read", { path: "src/app.ts" }), call(2, "snout_read", { path: "src/client.gen.js" })]);
  assert.equal(r[1].result.content[0].text, "export const a = 1;\nexport const b = 2;\n");
  const gen = r[2].result.content[0].text;
  assert.match(gen, /Showing lines 1–\d+ of 2001/);
  assert.match(gen, /op0 L2/, "carries the outline");
  assert.ok(gen.length < 10_000, `trimmed view is small, got ${gen.length}`);
});

test("mcp: a ranged read returns exactly that range", () => {
  const r = session(project(), [call(1, "snout_read", { path: "src/client.gen.js", offset: 10, limit: 3 })]);
  const text = r[1].result.content[0].text;
  assert.match(text, /lines 10–12 of 2001/);
  assert.equal(text.split("\n\n")[1].split("\n").length, 3);
});

test("mcp: secrets and paths outside the project are refused as tool errors", () => {
  const r = session(project(), [call(1, "snout_read", { path: ".env" }), call(2, "snout_read", { path: "../../etc/passwd" }), call(3, "snout_read", { path: "missing.ts" })]);
  for (const id of [1, 2, 3]) assert.equal(r[id].result.isError, true);
  assert.match(r[1].result.content[0].text, /secret/);
  assert.match(r[2].result.content[0].text, /inside the project/);
});

test("mcp: snout_classify names the label and the cost", () => {
  const r = session(project(), [call(1, "snout_classify", { path: "package-lock.json" }), call(2, "snout_classify", { path: "src/app.ts" })]);
  assert.match(r[1].result.content[0].text, /lockfile · confidence 1\.00 · band act/);
  assert.match(r[2].result.content[0].text, /source · band read/);
});
