import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { tier0, decide, applyMode, DEFAULTS } from "../dist/lib.mjs";

const root = mkdtempSync(join(tmpdir(), "snout-t0-"));
const cfg = DEFAULTS;

function file(rel, contents = "x") {
  const abs = join(root, rel);
  mkdirSync(join(abs, "..").replace(/\/\.\.$/, ""), { recursive: true });
  mkdirSync(abs.slice(0, abs.lastIndexOf("/")), { recursive: true });
  writeFileSync(abs, contents);
  return abs;
}

function classify(rel, contents = "x") {
  return tier0({ absPath: file(rel, contents), projectDir: root, cfg });
}

test("lockfiles are low value", () => {
  const d = classify("package-lock.json", "{}");
  assert.equal(d.rule, "lockfile");
  assert.equal(d.value, 0);
  assert.equal(d.verdict, "deny");
});

test("binaries are low value", () => {
  assert.equal(classify("assets/logo.png").rule, "binary");
});

test("vendored trees are low value", () => {
  assert.equal(classify("node_modules/left-pad/index.js").rule, "vendored");
  assert.equal(classify("src/__pycache__/mod.pyc").rule, "binary"); // extension wins, still low
});

test("minified output and source maps are low value", () => {
  assert.equal(classify("public/app.min.js").rule, "minified");
  assert.equal(classify("public/app.js.map").rule, "minified");
});

test("a generated marker in the head is detected", () => {
  const d = classify("src/api-client.ts", "/* eslint-disable */\n// @generated by openapi\nexport const x = 1;\n");
  assert.equal(d.rule, "generated");
  assert.equal(d.value, 0);
});

test("oversized files are marginal, not denied", () => {
  const d = classify("src/huge.ts", "a".repeat(DEFAULTS.sizeCapBytes + 10));
  assert.equal(d.rule, "oversized");
  assert.equal(d.verdict, "ask");
  assert.equal(d.value, 1);
});

test("snapshots are marginal", () => {
  assert.equal(classify("src/__snapshots__/a.test.ts.snap").value, 1);
});

test("ordinary source falls through to the next tier", () => {
  assert.equal(classify("src/auth/session.ts", "export const a = 1;"), null);
});

test("RULE ORDER: a secret outranks the always-allow list", () => {
  const withEnvAllowed = { ...cfg, alwaysAllow: [...cfg.alwaysAllow, ".env"] };
  const d = tier0({ absPath: file(".env", "KEY=1"), projectDir: root, cfg: withEnvAllowed });
  assert.equal(d.rule, "secret", "a credential must never be allowed by a glob");
  assert.equal(d.verdict, "ask");
});

test("RULE ORDER: the always-allow list outranks our heuristics", () => {
  const c = { ...cfg, alwaysAllow: ["package-lock.json"] };
  const d = tier0({ absPath: file("package-lock.json", "{}"), projectDir: root, cfg: c });
  assert.equal(d.rule, "always-allow");
  assert.equal(d.verdict, "allow");
});

test("a path outside the project is still classified", () => {
  const d = tier0({ absPath: "/etc/hosts", projectDir: root, cfg });
  assert.ok(d === null || typeof d.rule === "string");
});

test("a missing file does not throw", () => {
  assert.doesNotThrow(() => tier0({ absPath: join(root, "nope/none.ts"), projectDir: root, cfg }));
});

test("output dirs count only when .gitignore ignores them", () => {
  const repo = mkdtempSync(join(tmpdir(), "snout-t0-gi-"));
  const at = (rel, body = "x") => {
    const abs = join(repo, rel);
    mkdirSync(abs.slice(0, abs.lastIndexOf("/")), { recursive: true });
    writeFileSync(abs, body);
    return tier0({ absPath: abs, projectDir: repo, cfg })?.rule ?? "unclassified";
  };
  at(".gitignore", "dist/\n/coverage\nbuild\n!**/src/**/build\n");
  assert.equal(at("dist/bundle.js"), "vendored");
  assert.equal(at("packages/a/dist/index.js"), "vendored"); // unanchored: any depth
  assert.equal(at("coverage/lcov.info"), "vendored");
  assert.equal(at("cli/tools/coverage/mod.ts"), "unclassified"); // `/coverage` is root-only
  assert.equal(at("build/gulpfile.ts"), "vendored");
  assert.equal(at("buildSrc/src/main/java/org/x/build/Library.java"), "unclassified"); // negated
  assert.equal(at("out/main.js"), "unclassified"); // not ignored: committed output-named dirs are source
});

test("committed build/ with no .gitignore is not denied", () => {
  // vscode's build/ and kubernetes's build/ hold hand-written tooling (bench/label.mjs).
  assert.equal(classify("build/gulpfile.vscode.ts")?.rule ?? "unclassified", "unclassified");
});

test("generator banners bench/label.mjs found missing", () => {
  assert.equal(classify("src/any/q.rs", "//! This is a generated file. Don't modify it by hand! Run 'cargo codegen formatter'.\nuse x;\n").rule, "generated");
  assert.equal(classify("Rx/Zip+arity.swift", "// This file is autogenerated. Take a look at `Preprocessor` target\nimport X\n").rule, "generated");
  assert.equal(classify(".github/workflows/docs.lock.yml", "# gh-aw-metadata: {}\nname: x\n").rule, "generated");
});

test("built docs and third-party notices bench/label.mjs found missing", () => {
  const jazzy = '<!DOCTYPE html>\n<html>\n<head>\n<link rel="stylesheet" type="text/css" href="../css/jazzy.css" />\n</head>\n';
  assert.equal(classify("docs/Classes/Request.html", jazzy).rule, "generated");
  assert.equal(classify("docs/X.docset/Contents/Resources/Documents/index.html", "<html></html>\n").rule, "generated");
  assert.equal(classify("ThirdPartyNotices.txt", "NOTICES\n\nThis repository incorporates material...\n").rule, "license");
  assert.equal(classify("docs/index.html", '<html><head><link rel="stylesheet" href="site.css"></head></html>\n'), null, "a hand-written page stays silent");
  assert.equal(classify("docs/jazzy.md", "Notes on the jazzy.css theme.\n"), null, "mentioning jazzy is not being jazzy output");
});

test("Track A's three harmful trims stay readable; real banners and root deps/ still trim", () => {
  const ciScript = '#!/bin/bash\n#\n# Verify that every Markdown file under directories that ESQL tests\n# manage as fully-generated content carries the standard "this is\n# generated, do not edit" header.\n#\nset -euo pipefail\n';
  assert.equal(classify(".ci/scripts/check-esql-generated-headers.sh", ciScript), null, "a script describing a banner is not one");
  assert.equal(classify("scripts/build/deps/brotli.ts", "/** Brotli build recipe. */\nimport type { Dependency } from '../source.ts';\n"), null, "nested deps/ is not vendored");
  assert.equal(classify("deps/zlib/zlib.h", "/* zlib.h -- interface of the 'zlib' general purpose compression library */\n").rule, "vendored", "root deps/ still is");
  assert.equal(classify("test/fixtures/sample_project/README.rst", "Sample project\n==============\n"), null, "hand-written fixtures are not asked about");
  assert.equal(classify("src/__snapshots__/view.test.ts.snap", "// Jest Snapshot v1\nexports[`x`] = `1`;\n").rule, "snapshot", "recorded snapshots still are");
});
