/** Library entry point. Exists so tests can import internals without running the CLI. */
export { tier0, scoreFile, toRel, sizeOf, fingerprintOf } from "./gate/tier0.js";
export { decide, applyMode, bandOf, withOverride, searchHint, THRESHOLDS } from "./gate/decide.js";
export { firstHit, scoreLabels, labelOf, parseGitignore, ignoredOutputDirIn, LABELS, HINT_SCORE } from "./gate/rules.js";
export { summarize } from "./gate/summary.js";
export { readTargets, dumpTargets } from "./gate/bash.js";
export { responseText, responseBytes } from "./gate/response.js";
export { splitGrepOutput } from "./gate/grep.js";
export { DEFAULTS, loadConfig, resolvePaths, attach, ensureDir, isValidMode } from "./config.js";
export { estimateTokens, ratioFor, readTranscriptUsage, fmtTokens } from "./ledger/tokens.js";
export { appendRow, readRows, readDecisions, dropEchoes, readTurns, loadState, saveState } from "./ledger/store.js";
export { renderReport, totalsOf, percentile, harnessOf, byAgentOf, agentLabel, redundancyOf, JEV_USD_PER_MTOK } from "./ledger/report.js";
export { renderStatusline } from "./ledger/statusline.js";
export { tipsOf, claudeMdLine } from "./ledger/tips.js";
export { matchesAny, toRegExp } from "./util/glob.js";
export { safePath, safeText, looksCrafted } from "./util/safe.js";
export { writeAtomic } from "./util/atomic.js";
export { tailLines } from "./util/tail.js";
export { snoutignore } from "./gate/tier0.js";
export { rotateIfLarge, DEFAULT_LIMIT, MAX_LIMIT } from "./ledger/store.js";
export { PINNED_MODEL } from "./config.js";
export type * from "./types.js";
export { outline } from "./gate/outline.js";
export { summarizeLedger, dailyAggregates, type DashboardSummary, type DayRow } from "./dashboard/summary.js";
export { claudeRequests, codexRequests, readSpend, claudeSlug } from "./spend/usage.js";
export { costOf, priceOf, modelKey, PRICES, PRICES_AS_OF } from "./spend/prices.js";
export { summarizeSpend } from "./spend/summary.js";
export { scorePrompt } from "./coach/coach.js";
export { squeeze, kindOf, SQUEEZE_IFS } from "./squeeze/squeeze.js";
export { gateEntries, squeezeEntries } from "./gate/install.js";
export { trimMcp } from "./squeeze/mcp.js";
export { auditContext, classifyContextPath, staleRefs, normalize, shingles, overlap, authorOf, readClaudeTranscript, renderAudit, renderMap, toJson, totals, archiveFiles, restoreArchive, listArchives, OVERSIZED_TOKENS } from "./audit/context.js";
export { buildMap, candidates, renderCandidates, requestNames, listFiles, entryFor, type RepoMap, type Candidate } from "./map/map.js";
